## ????????
server:
  port: 8888
  servlet:
    context-path: /crm
## ?????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #????druid???
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/templates/
    settings:
      classic_compatible: true

  ## ?????
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
## mybatis ??
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xxxx.crm.vo;com.xxxx.crm.query;com.xxxx.crm.dto
  configuration:
    map-underscore-to-camel-case: true

## pageHelper
pagehelper:
  helper-dialect: mysql

## ?? dao ??????
logging:
  level:
    com:
      xxx:
          dao: debug
